# Site settings
title: Geo for Teachers 
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: mapconcierge
baseurl: "/geo4teachers/" # the subpath of your site, e.g. /blog/
url: "https://furuhashilab.github.io" # the base hostname & protocol for your site
